import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));
const context={};vm.runInNewContext(fs.readFileSync(path.join(dir,'catalog.js'),'utf8'),context);
const {variants,palettes}=context.MBCatalog;
for(const v of variants)fs.writeFileSync(path.join(dir,v.id+'.html'),`<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>${v.name} — MediaBoxManager</title><link rel="stylesheet" href="base.css"><link rel="stylesheet" href="tide.css"><link rel="stylesheet" href="palettes.css"><link rel="stylesheet" href="extra-palettes.css"><link rel="stylesheet" href="usability.css"><link rel="stylesheet" href="operator.css"><link rel="stylesheet" href="tide-family.css">${v.id==='tide'?'':`<link rel="stylesheet" href="${v.id}.css">`}</head><body data-design="tide" data-variant="${v.id}" data-palette="${v.palette}"><div id="app"></div><script src="catalog.js"></script><script src="schedule-model.js"></script><script src="app.js"></script></body></html>`);
fs.writeFileSync(path.join(dir,'extra-palettes.css'),'/* Eight additional palettes. Generated from catalog.js. */\n'+palettes.filter(p=>p.isNew).map(p=>`body[data-design][data-palette="${p.id}"] {
--accent:${p.color};--accent-soft:color-mix(in srgb,${p.color} 10%,white);--bg:color-mix(in srgb,${p.color} 4%,#f5f6f7);--surface:#fff;--surface-2:color-mix(in srgb,${p.color} 6%,white);--ink:#28323c;--muted:#63717e;--line:color-mix(in srgb,${p.color} 15%,#e8ebee);
--art-1:color-mix(in srgb,${p.color} 10%,white);--art-2:color-mix(in srgb,${p.color} 25%,white);--art-3:color-mix(in srgb,${p.color} 45%,white);--art-4:color-mix(in srgb,${p.color} 75%,white);--art-5:${p.color};--art-alt:color-mix(in srgb,${p.color} 30%,#d7e5ed);--shadow-rgb:63 76 94;
}`).join('\n'));
fs.writeFileSync(path.join(dir,'index.html'),`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Прилив — шесть вариантов и шестнадцать палитр</title><link rel="stylesheet" href="base.css"><link rel="stylesheet" href="tide-gallery.css"></head><body><main><header><a class="brand" href="index.html"><span class="brand-mark">m</span>MediaBoxManager</a><nav><a href="coverage.html">Функции</a><a href="sources.html">Референсы</a><a href="../DESIGN.md">Памятка</a></nav></header><section class="intro"><div><div class="eyebrow">Выбранная композиция · Прилив</div><h1>Один Прилив.<br>Шесть вариантов.</h1></div><p><strong>Широкое расписание, каналы слева и медиатека внизу.</strong> Оригинал и пять новых оформлений по вашим референсам. Светлые материалы, разные контролы и одна знакомая логика работы.</p></section><section class="palette-bar" aria-label="Палитры для сравнения"><div class="palette-copy"><strong>16 палитр · 8 новых</strong><small>Палитра применяется при открытии варианта</small></div><div class="swatches">${palettes.map(p=>`<button class="swatch" data-palette-choice="${p.id}" data-new="${!!p.isNew}" style="--swatch:${p.color}" aria-label="${p.name}${p.isNew?' — новая':''}" title="${p.name}${p.isNew?' · новая':''}"></button>`).join('')}</div><label class="palette-choice"><select id="comparison-palette" aria-label="Палитра для сравнения"><option value="">Палитра каждого варианта</option>${palettes.map(p=>`<option value="${p.id}">${p.name}${p.isNew?' · новая':''}</option>`).join('')}</select></label></section><section class="collection">${variants.map((v,i)=>`<a class="concept" data-variant-link="${v.id}" href="${v.id}.html"><div class="screen" style="--tint:${palettes.find(p=>p.id===v.palette).color}13"><img src="previews/${v.id}.png" alt="${v.name}: рабочий экран" loading="eager"></div><div class="concept-heading"><h2><span class="concept-number">0${i+1}</span>${v.name}</h2><span class="arrow" aria-hidden="true">↗</span></div><p>${v.description}</p><small>${v.material}</small></a>`).join('')}</section><footer class="note"><p>В каждом варианте доступны все шестнадцать палитр. Переключатели «Вариант» и «Палитра» находятся в верхней панели. Данные демонстрационные; команды MediaBoxPlayer имитируются.</p><a href="coverage.html">Карта функций →</a></footer></main><script src="gallery-controls.js"></script></body></html>`);
fs.writeFileSync(path.join(dir,'references.html'),'<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=index.html"><title>Прилив — варианты</title></head><body><a href="index.html">Открыть шесть вариантов Прилива</a></body></html>');
console.log('Built Tide original + five variants, sixteen palettes and gallery.');
