add_library(MediaBoxPaths STATIC storagepaths.cpp storagepaths.h)
target_include_directories(MediaBoxPaths PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
target_compile_features(MediaBoxPaths PUBLIC cxx_std_23)
target_link_libraries(MediaBoxPaths PUBLIC Qt6::Core)
if(WIN32)
    target_link_libraries(MediaBoxPaths PRIVATE shell32)
endif()
if(MSVC)
    target_compile_options(MediaBoxPaths PRIVATE /utf-8 /permissive- /Zc:__cplusplus)
endif()
